### ISSUE TITLE
Certificate pinning

### ISSUE THREAD

**Issue by langboost** [smndtrl/Signal-UWP#16]
Since we're already storing .cer files for staging and prod, we should consider adding code to check the certificate's public key, and fail if it doesn't match our local copy in the app.

**Comment by langboost** [comment]
See https://www.owasp.org/index.php/Certificate_and_Public_Key_Pinning for an explanation.

**Comment by smndtrl** [comment]
Thats what the extensions is for. it trusts only the certs i provided..

**Comment by langboost** [comment]
I wasn't sure if it trusted ONLY the certs you provided. If you're certain of that, works for me.

**Comment by smndtrl** [comment]
It is supposed to. Haven't validated it yet. the TrustStore tag should keep app-local store with only our certs

**Comment by langboost** [comment]
Sounds good. I'm away from the dev box this week, otherwise I'd help you check. Thanks!
