### ISSUE TITLE
get ui to feel more like the "windows-way"

### ISSUE THREAD

**Issue by AndHell** [smndtrl/Signal-UWP#18]
I know the project is in an early stage.
But maybe that would made it easier to change to UI at some points.
What I mean with "windows-way" from the titel is for example to use the pivot item to display open chats and contacts.
On phone that would allow you to simply swip right/left to change few.
Like in WhatsApp or telegram. I think this is more familiar to windows phone users.

If whished I could try to implement this.

What do you think about this?

**Comment by smndtrl** [comment]
What pivots would you want? One for active chats, one for archived chats and one for contacts? With the current ui i tried to mimic the default messaging app on windows phone.

**Comment by AndHell** [comment]
I think contacts and active chats would be ok.

Archived chats could be behind a secondary AppBarButton.
(you archive them to get them away of your list so putting them next to the active chats would not really be that effective)

**Comment by AndHell** [comment]
https://github.com/AndHell/Signal-UWP/tree/overworkUI

This is was i was thinking about. 
It's not completely working and the code is just copy past and need to be cleaned up. But i think it's OK to show how it can look like.
